---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tradesca/public_html/
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp -R README.md $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    ---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tradesca/public_html/
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp -R solar-instant-quote.php $DEPLOYPATH
    - /bin/cp -R README.md $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH